[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_OPTIONS="--max-old-space-size=8192" }

  
[[redirects]]
  from = "/gatographql-vs-wprestapi"
  to = "/comparisons/gatographql-vs-wp-rest-api"
  status = 301

[[redirects]]
  from = "/gatographql-vs-wp-rest-api"
  to = "/comparisons/gatographql-vs-wp-rest-api"
  status = 301

[[redirects]]
  from = "/gatographql-vs-wpgraphql"
  to = "/comparisons/gatographql-vs-wpgraphql"
  status = 301
  
[[redirects]]
  from = "/tags"
  to = "/blog"
  status = 301
  
[[redirects]]
  from = "/tags/*"
  to = "/blog"
  status = 301
  
[[redirects]]
  from = "/recipes/*"
  to = "/tutorial/:splat"
  status = 301

[[redirects]]
  from = "/demo"
  to = "/tutorial/intro"
  status = 301

[[redirects]]
  from = "/about-us"
  to = "/about"
  status = 301

[[redirects]]
  from = "/guides/special-features/*"
  to = "/features/:splat"
  status = 301

[[redirects]]
  from = "/guides/intro"
  to = "/guides/intro/intro-to-graphql-and-gato-graphql"
  status = 301

[[redirects]]
  from = "/guides/query"
  to = "/guides/query/executing-queries-and-mutations"
  status = 301

[[redirects]]
  from = "/guides/use"
  to = "/guides/use/creating-a-custom-endpoint"
  status = 301

[[redirects]]
  from = "/guides/schema"
  to = "/guides/schema/namespacing-the-schema"
  status = 301

[[redirects]]
  from = "/guides/config"
  to = "/guides/config/installing-and-upgrading-a-bundle-or-extension"
  status = 301

[[redirects]]
  from = "/guides/augment"
  to = "/guides/augment/schema-extensions-via-introspection"
  status = 301

[[redirects]]
  from = "/guides/interact"
  to = "/guides/interact/working-with-custom-posts"
  status = 301

[[redirects]]
  from = "/guides/deep"
  to = "/guides/deep/fetching-dynamically-structured-data"
  status = 301

[[redirects]]
  from = "/guides/resources"
  to = "/guides/resources/graphql-best-practices"
  status = 301

[[redirects]]
  from = "/tutorial/complementing-wp-cli"
  to = "/guides/code/complementing-wp-cli"
  status = 301

[[redirects]]
  from = "/tutorial/dry-code-for-blocks-in-javascript-and-php"
  to = "/guides/code/dry-code-for-blocks-in-javascript-and-php"
  status = 301

[[redirects]]
  from = "/tutorial/exposing-public-and-private-endpoints"
  to = "/guides/code/exposing-public-and-private-endpoints"
  status = 301

[[redirects]]
  from = "/tutorial/feeding-data-to-blocks-in-the-editor"
  to = "/guides/code/feeding-data-to-blocks-in-the-editor"
  status = 301

[[redirects]]
  from = "/tutorial/injecting-multiple-resources-into-wp-cli"
  to = "/guides/code/injecting-multiple-resources-into-wp-cli"
  status = 301

[[redirects]]
  from = "/tutorial/mapping-js-components-to-gutenberg-blocks"
  to = "/guides/code/mapping-js-components-to-gutenberg-blocks"
  status = 301

[[redirects]]
  from = "/bundles"
  to = "/"
  status = 301

[[redirects]]
  from = "/bundles/all-in-one-toolbox-for-wordpress"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/automated-content-translation-and-sync-for-wordpress-multisite"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/better-wordpress-webhooks"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/easy-wordpress-bulk-transform-and-update"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/private-graphql-server-for-wordpress"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/responsible-wordpress-public-api"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/selective-content-import-export-and-sync-for-wordpress"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/simplest-wordpress-content-translation"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/tailored-wordpress-automator"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/unhindered-wordpress-email-notifications"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/bundles/versatile-wordpress-request-api"
  to = "/"
  status = 301

[[redirects]]
  from = "/bundles/content-translation"
  # to = "/bundles/simplest-wordpress-content-translation"
  to = "/"
  status = 301

[[redirects]]
  from = "/bundles/public-api"
  # to = "/bundles/responsible-wordpress-public-api"
  to = "/"
  status = 301

[[redirects]]
  from = "/bundles/application-glue-and-automator"
  # to = "/bundles/tailored-wordpress-automator"
  to = "/"
  status = 301

[[redirects]]
  from = "/bundles/all-extensions"
  # to = "/bundles/all-in-one-toolbox-for-wordpress"
  to = "/"
  status = 301

# Campaigns
[[redirects]]
  from = "/raffle"
  to = "/"
  status = 302

[[redirects]]
  from = "/black-friday"
  to = "/"
  status = 302

[[redirects]]
  from = "/wpbuilds"
  to = "/specials/wpbuilds"
  status = 301

# Docs migrated from graphql-by-pop.com

[[redirects]]
  from = "/docs/dynamic-schema/ifttt-through-directives.html"
  to = "/architecture/ifttt-through-directives"
  status = 301
  
[[redirects]]
  from = "/docs/dynamic-schema/field-directive-based-versioning.html"
  to = "/architecture/field-directive-based-versioning"
  status = 301

[[redirects]]
  from = "/docs/architecture/cms-agnosticism.html"
  to = "/architecture/cms-agnosticism"
  status = 301

[[redirects]]
  from = "/docs/architecture/solid.html"
  to = "/architecture/solid"
  status = 301

[[redirects]]
  from = "/docs/architecture/code-first.html"
  to = "/architecture/code-first"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/dataloading-engine.html"
  to = "/architecture/dataloading-engine"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/decoupling-queries.html"
  to = "/architecture/decoupling-queries"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/directive-design.html"
  to = "/architecture/directive-design"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/directive-pipeline.html"
  to = "/architecture/directive-pipeline"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/manipulating-field-resolution-order.html"
  to = "/architecture/manipulating-field-resolution-order"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/nested-mutations-single-source-of-code.html"
  to = "/architecture/nested-mutations-single-source-of-code"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/schema-type-directives.html"
  to = "/architecture/schema-type-directives"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/subscribing-fields-to-types.html"
  to = "/architecture/subscribing-fields-to-types"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/suppressing-n-plus-one-problem.html"
  to = "/architecture/suppressing-n-plus-one-problem"
  status = 301
  
[[redirects]]
  from = "/docs/architecture/using-components-instead-of-graphs.html"
  to = "/architecture/using-components-instead-of-graphs"
  status = 301
  
[[redirects]]
  from = "/guides/rapid-iteration-on-the-schema.html"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/guides/versioning-fields-and-directives.html"
  to = "/features/field-and-directive-based-versioning"
  status = 301
  
[[redirects]]
  from = "/guides/localized-newsletter.html"
  to = "/"
  status = 301
  
[[redirects]]
  from = "/guides/building-cms-agnostic-api.html"
  to = "/architecture/cms-agnosticism"
  status = 301

[[redirects]]
  from = "/docs/architecture/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/caching/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/clients/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/dynamic-schema/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/extended/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/getting-started/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/going-further/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/operational/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/roadmap/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/schema-objects/*"
  to = "/"
  status = 301

[[redirects]]
  from = "/docs/troubleshooting/*"
  to = "/"
  status = 301


# Proxying Plausible through Netlify
# @see https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
  from = "/masked-source/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200

[[redirects]]
  from = "/masked-source/api/event"
  to = "https://plausible.io/api/event"
  status = 200

# Download file redirects
[[redirects]]
  from = "/releases/latest/gatographql-testing-schema.zip"
  to = "https://github.com/GatoGraphQL/GatoGraphQL/releases/download/4.0.0/gatographql-testing-schema-4.0.0.zip"
  force = true
  status = 302

[[redirects]]
  from = "/releases/latest/gatographql-testing.zip"
  to = "https://github.com/GatoGraphQL/GatoGraphQL/releases/download/4.0.0/gatographql-testing-4.0.0.zip"
  force = true
  status = 302

[[redirects]]
  from = "/releases/latest/gatographql.zip"
  to = "https://github.com/GatoGraphQL/GatoGraphQL/releases/download/4.0.0/gatographql-4.0.0.zip"
  force = true
  status = 302

[[redirects]]
  from = "/releases/latest"
  # to = "https://github.com/GatoGraphQL/GatoGraphQL/releases/download/4.0.0/gatographql-4.0.0.zip"
  # to = "https://downloads.wordpress.org/plugin/gatographql.4.0.0.zip"
  to = "https://downloads.wordpress.org/plugin/gatographql.latest-stable.zip"
  force = true
  status = 302
